# Generated by Django 3.1.5 on 2021-05-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210516_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default='', upload_to='uploads/files'),
        ),
    ]
